name: q-py-data
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - tornado
  - numpy
  - pip
  - pandas
  - matplotlib
  - h5py
  - imageio
  - scipy
  - opencv
  - pip:
    - tables
